#!/usr/bin/env bash

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

if [[ $# -lt 1 ]]; then
    echo usage: $0 PLAYBOOK [ANSIBLEARGS...]
    exit 1
fi

playbook=$1
shift

[[ -e playbook-$playbook.yml ]] >/dev/null 2>&1 || { echo >&2 "playbook-$playbook.yml is not a playbook"; exit 1; }
command -v virtualenv >/dev/null 2>&1 || { echo >&2 "virtualenv not installed"; exit 1; }

VENV_PATH=${VENV_PATH:-.venv}

if [[ ! -e $VENV_PATH ]]; then

    virtualenv -p python3 $VENV_PATH
    source $VENV_PATH/bin/activate
    pip3 install -r requirements.txt

else

    source $VENV_PATH/bin/activate

fi

command -v ansible-playbook >/dev/null 2>&1 || { echo >&2 "ansible-playbook not installed"; exit 1; }
command -v ansible-galaxy >/dev/null 2>&1 || { echo >&2 "ansible-galaxy not installed"; exit 1; }

ANSIBLE_USER=${ANSIBLE_USER:-dragon}
CLEANUP=${CLEANUP:-false}

if [[ ! -e roles ]]; then

    ansible-galaxy install -f -r requirements.yml

    # https://stackoverflow.com/a/122340/99834
    lib=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

    cp -r $lib/debops/ansible/roles/debops.grub roles/
    cp -r $lib/debops/ansible/roles/debops.secret roles/
    cp -r $lib/debops/ansible/roles/debops.ansible_plugins roles/

fi

if [[ ! -e id_rsa.operator ]]; then

    ansible-playbook \
        -i localhost, \
        -e @../secrets.yml \
        playbook-keypair.yml "$@"

fi

ansible-playbook \
    --private-key id_rsa.operator \
    -i hosts \
    -e @../images.yml \
    -e @../configuration.yml \
    -e @../secrets.yml \
    -e @images.yml \
    -e @configuration.yml \
    -u $ANSIBLE_USER \
    playbook-$playbook.yml "$@"

if [[ $CLEANUP == "true" ]]; then

    rm -rf roles
    rm id_rsa.operator
    rm -rf $VENV_PATH

fi
