#!/usr/bin/env bash

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

[[ -e playbook-$1.yml ]] >/dev/null 2>&1 || { echo >&2 "playbook-$1.yml is not a playbook"; exit 1; }
command -v pip >/dev/null 2>&1 || { echo >&2 "pip not installed"; exit 1; }
command -v virtualenv >/dev/null 2>&1 || { echo >&2 "virtualenv not installed"; exit 1; }

if [[ ! -e .venv ]]; then
    virtualenv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
else
    source .venv/bin/activate
fi

command -v ansible-playbook >/dev/null 2>&1 || { echo >&2 "ansible-playbook not installed"; exit 1; }
command -v ansible-galaxy >/dev/null 2>&1 || { echo >&2 "ansible-galaxy not installed"; exit 1; }

ANSIBLE_USER=${ANSIBLE_USER:-dragon}
CLEANUP=${CLEANUP:-false}

if [[ ! -e roles ]]; then
    ansible-galaxy install -f -r requirements.yml
fi

if [[ ! -e id_rsa.operator ]]; then
    ansible-playbook \
        -i localhost, \
        -e @../secrets.yml \
        playbook-keypair.yml
fi

ansible-playbook \
    --private-key id_rsa.operator \
    -i hosts \
    -e @../images.yml \
    -e @../configuration.yml \
    -e @../secrets.yml \
    -e @images.yml \
    -e @configuration.yml \
    -u $ANSIBLE_USER \
    playbook-$1.yml

if [[ $CLEANUP == "true" ]]; then
    rm -rf roles
    rm id_rsa.operator
    rm -rf .venv
fi
