---
- secret:
    name: SECRET_CFG_GENERICS
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - BsQrkFNqPkySHwnPDeLZfQmuAeplSzVui2c+NzUpAsYShEn2C9PPlqrv+H+IckjoOqV2l
          bXhkUubdkEG77FYUi3O/7Imcw3QU/6E2Kd8+UHEWZYFaHmNo10VsAPy957XygHOEqWBXt
          iY8M8hlSv2GdKtbAoIwjFgaL7EHmSocbEKl6//SSp9KcehhkwBdkMoW+k7RRLnzPxHDya
          FYSc5QFdj2xO3YiOs/vuinuD1HK7IkTGstPjnEuLyMA4l3Pf8qnI6nFrHSlRmRd3405Ct
          b31wvpkgzWsTqHHBNczIyj85gVCGiG0vxoM3UVb4UIeskTzQj5VGx0SZ4MkxQBTcIkzTm
          p57Gaj8YxU31d7I5w5L2xiQp1REt2osf4MXrUGugWqHO0+HVCQXXEPhPJEtxmqEMKu+B5
          5ZONNcSNkrlxmIvaNlE+u1fFbinyMQWf5DaiauvHa2l+w2yfkhnYRyBPiHtZWBYzoUeBb
          4TYnqdw98/uGdw3yME5VN5cLrzXx6TwkRE6Vy8I2+xvTPDjwNV8raot9pP2vKYVqT3I7I
          inwtBk3K6YBuyq4MHEhu4N4WnwhrWcbPWQXUxOw3vy4WMQhWeFWJwDF2gdzUS2feZjJtp
          kI2X5kBumyuQ+qnsD9SjadFA25yWhuGpUrItIueDcJLKd85mWJ3CbKtRRryMNI=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - FWcWLB7DCgOmpuFTkr6Bai3ML9oR6WpNhIFfs+HGGBsxNZFCUQVyFVzlyOJvcFlvAVW2F
          XMZD4D+9h7TFxPNAMcQPLk5o2nqbRwxU7tZG9tbMVdTRx+RG1KZrMi6WoXrrD7mgs973l
          RTeHz7+ecwj3mFp1ahlwwG1p6qEQFeuoNSVn0o18LWeER6T5jkSoZQyxYlkRUdEUoL3fZ
          351TqgkRVTwVoWlxut2PE2zryF4A23rXwz8aIB+5/m1VUcdogs7bfRINOGl6HDC6wUw4q
          khOGePmR5YcF/CJbZgwy1v4LKSHreENEu7Jyc9zXIQcgjTew9OP35An/kDs8DEGbRseIq
          n9waDG3UOFpzFotTO0ul0anNu24u1/mTBMn+Ujw/YS0YptkMGX15rKkRNeGv4Pr881BZg
          AO4ITQj/7AOa2poLxnc2ELHg+5V+dNvdN/WBZ98LYBf+PB6fmaXSgD/pUmZzzD6wfGqPN
          rlwP/+PBOjau5D2IjWq8Chsk/BXD/ZesDI7jWEFQqNKtGabfpUtyOXC22kecPtxOnpXXl
          xM/rLo3LLfiZNqi0fyNOFFkTCimbav2oub4PGQE0ok3GFqa2CpS5BcoouFVdXA8JNGsUS
          CTbmMwqpycbYX0xfaFxvLNa2WN/7vKhftwtgAhMdFrhi7HxAXqzDwOjdZwZIAY=

- job:
    name: cfg-generics-tox
    parent: tox
    vars:
      tox_envlist: gilt

- job:
    name: cfg-generics-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_CFG_GENERICS
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - cfg-generics-tox
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    gate:
      jobs:
        - cfg-generics-tox
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - cfg-generics-tox
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    post:
      jobs:
        - cfg-generics-container-image-osism-ansible-push:
            branches: main
