---
- secret:
    name: SECRET_CFG_GENERICS
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - W9F3X9Ai9XKWOvPDmTlUy3gmgl866q76nYlKqlvxsUZJNHcPVlfA9P7yGEBEalc7a21NH
          4K/G3j9QgPpWNu3wD8xfLhNZgjWxtB5Om4Pp6OjYbMnczp4R9LxWvnJxhmmYka0dKqJnn
          Yyg3MP7x9p6eAYzEGCfTZAWkWaSQz8S2Z/INzDlBsA32di2UyQU4o7sbj8TAnWx8wUTIk
          e/sM1Sa3DJj2USxmhizD7IYzeFBf2i12UlWrAC/aMpE8Tyil19qUCmRoHgmUrIDr1ARUF
          msFblyv3jWtWFBCml0XO72I1YMp1mVSI6C77syQOY89zAmo6Mwm/u+x0LLvGaKI7sDbv6
          ZP8FXr1c2Tl1qQENEKqN3QSf0mcBC9gZ5IIssThGH29HO//VHHhRMoLyzUnHeyX2zILyc
          B91v6bg2xHm/v/9T/Y9HTQ+vvBYWXMSex0wJxA0LFgm2pywNIzbO3PTMJDbGbjts9p9wM
          eyF59uNXDe33tMcC4fodxvROOMYQyAeV4uNkwW0tM8BhSWIjpZwW+3I77kT6ydI8VcIoA
          BIt8oe6GOM5kfhjfRXTEvSp8DZT8tdAv1o92Tw7u2j92FGBRnIeCaxbeTLhx2oRvsWOF1
          kriEeHk24tDb/nlGT1D/Iw8tUBiZUDl1hXLZ+6prNFJeKa9hEsQ2caJOvOvgOY=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - SEu4lL+uBvWQS0z/P+cp8pWJ/qdNqUBq+1t7f0HYdsgGgPHfINVhk1RaC73HDp2ejiBtH
          qUAZglnIo7eqolAKOCVgDyCmhoBEYa5JOBeJoJ5ReNvoqlGEHS+VTrnZ9TUQOTm0tyr/h
          u3Q+E5zx9W5a9l+ks3cB8HVBn2CT5m/X4t994rivosaEbJLbYIm4cZ8PirB9m1IpGwW+O
          2afrJH+WYn7bXcsJ1Y69Y52fjyZxhhXmbDaIwpdZzLJJOV3JqM1L00W7qtc/5xGp9HV6b
          uOQsSdOm2Ms3Fm8m/bwKr1koLZflNog7md/25+haABv+5z9sIibkU/lx8/mtV9EoBIi8n
          +g+P53TLhn0Bc+NEgnC9T8m5OOOCb1QySbnAN+s+JLe7p+NJX33tncd6NqIxJjQhZo6f6
          kFbQ/lZa1ze6VpQ2QjDFH5N/+ufeYlRfd+0dN+MfeZWQLsSAi9YXxEQGMWEcY9yQeELJo
          hWfWOvihtKaC0x2ZfGYYnkuO0NyATeBgJV+87jPzVntWycWVCRsMSkg4CZPvGeF4k1yo0
          SVtfH7ZuICFOjYzTyCKpkYbJYowpvgvB//3MKjT0ZHvGmhebi8cSHAM4P+lB2f9AgP1wY
          4rwU6IhEN6p4LIKgK19V7VedA/xE/OoU/RmC56K8H5izHEfACvxouhw03SMdl4=

- job:
    name: cfg-generics-tox-gilt
    parent: tox
    vars:
      BRANCH: "{{ zuul.branch }}"
      tox_envlist: gilt

- job:
    name: cfg-generics-tox-check
    parent: tox
    vars:
      BRANCH: "{{ zuul.branch }}"
      tox_envlist: check

- job:
    name: cfg-generics-container-image-inventory-reconciler-push
    parent: abstract-container-image-inventory-reconciler-push
    secrets:
      - name: secret
        secret: SECRET_CFG_GENERICS
        pass-to-parent: true

- job:
    name: cfg-generics-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_CFG_GENERICS
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    gate:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    post:
      jobs:
        - cfg-generics-container-image-inventory-reconciler-push:
            branches: main
        - cfg-generics-container-image-osism-ansible-push:
            branches: main
