---
- secret:
    name: SECRET_CFG_GENERICS
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - eu7kmcX0mY5B7mmTev0xBQUfFTU7335RbthWlWTLWdCwK/D+IfftoAwslv+bToP/Gb5k3
          n2ieLc8N49l5p5htYqxKdatRNpV98fdCkUje0kLU08/bLdV3ByaWM5MERRZFDRldja+hq
          /99uN+VTbYKSmVEfa2nXdMfK7a+83ck3fqxT7Rl1gfYEJo+XIWEu7aXFF2vtBr9o9hHH7
          gvCxI0kvXwUCOHRHC9JwH4wpDsF8XdQjpPvHwlP3dEvyyWbqND09DzoCaq7ic5Ra2sndG
          TctLtRuMoFV8Kp10MxPrswwRkF9rYARHGRxsdfLac0K/SFqQyFz+jZkXZT88ao+K/54uu
          R/qb5Aef6AM7vXnaYIss1s5486wmnHQzw+AQqP11aXuCLTlyCUcBIKNXt9wnoC6Kv86JK
          dF/2zzLAFtQYGZjFnc2f+fMn5Qr1lKtcw40YoWVP0Vd5U8n6xGHcCGM7up7tW/2Vpu+LE
          A1SVhlITVvVTuE3Q1qSAFt2pNQ8DYmSTxjI2qR/b5qvEWYxIqlHc4LbLJT96otq1OkwSi
          0acOaMGxp0n+PZSIcgPZvooEpwqqRGu0S1uHwJmRaeztAv4lkFOSmYNmL3Bv0PoFjcjpM
          XMROuZoxqH5H6Ocbnn+1WhmrHNsHdbWEXoqPxphfNkI36KavLgiO5iKwqHI79s=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - NYq4Q6VT0GZxA0BiN8mbzJgavCVd8mJ2Q1mhqARk0ToIg+KKqxRQk8AJcUXg8RatX+LkM
          /ctjdCFCxRPakdP0L4K6C2SQJIj68wA5B3bvcd1ZKN9VFd/VRvcMtDqaWRYkkx/5yaKFy
          T+fVAB0WfB4U7OtRndc8rCTKgtIw2X4D++FV25ZC4G2DOcVwkBuAZctGKTiv+11B2tyl9
          s8gdXkzmNMmxufOl/3rmKHZHcGhYQVOglEg4TR29Wtpf/LfSOKXdzlIuf6AC6zGN3OSXp
          nXOskWlL/WLVnBpNWAYoizf/gRKrBineU2qVULQIV9DYUkjIJzjRGZGSbm6pirI3hDDqq
          j0LdAedSC8e9CrsXiIsg4QcdSOvMVwjAOhMNGL8RvwJ1j7HGiYkZg/9g0jdJEkWIRm3A7
          A+o+Wd09nuGuB043nF6evSD/0L+sRJqSdyquTQn9NTK/mE1/6G6RlzSD5AnnDvAeK2KN3
          5mm3oYZktx3hX55ftzWruvxAnPtXTHubs+9LHGfDFv/dwhg2B38GajPMJ3MV+9eQrZ/QV
          2iUO6wKt7agvOD2guXXQ9Hdep6qcjn6mHekTP86QQn69looQ6TvdJtLdMyTduDYmNFeCu
          rCw2vJmkqI+xglinyCaIwNjvYF5Hc/wCrDNhqzJW/BvnsA23gpveDbjFGc25xs=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - DFpw6jl31Ey89P9ljb3H2od9obNF+g6+mnhY5z/7oF5YFoczalpsYGiccamn9v2gSUBvf
          gFMWLNNJNHThfnpAGigdRDefkYTH1oHAIq0kdqrMYHmOT3wNTGrcZUTBD4lLSu/rtD/pK
          Sd94We9GzSMR4jHL/yuJ/gWLADoVV2Z+JdkzqjUAOP4LOcA4D9jQlkKBURktdIdAfaG8E
          uAUVKbV4KrUwCxG4u+sgkEYcFGG0a5jTgg6+hA9GVLOcYSiV3WpzCJVvmkcmUq7k3wI7o
          j7938zFAjKXIgJgKyASWCAgCJ3fcxPkKCmwdUbG/IS9piVKZKIbaWcAGCrYa7rEW1f3xI
          b4/IwVa+9vR6ci3JOV5+qGsa2vJUcBc4VghpDBs5nCfjhjAugCVZTE0hVssCrcXNH6R+q
          qk4xdonlc96GAstAp7uIdA0rNZgWWiT58EVzHLZresGxh3T8gIDCBZZYFh50aUHaZUO6+
          +P9yviC2gmbPVtPs2h/iXPh0t4xxB/8M40A+w8/0IeezrAkfe5NL7MgeWlMKCfG90BOz1
          3/cRiaMr9gdN/YyEtZTNREapWy/m9L81VVlOFQW9Fn8/wEztG5hEcHq/L4F28dBV0vu8t
          2+rRLpef7j/V/tNGQQ9MfrmM5inGUF/FG8AdiM/+/ps12bDsE4JnPH6vyBmNlA=

- job:
    name: cfg-generics-tox-gilt
    parent: tox
    vars:
      BRANCH: "{{ zuul.branch }}"
      tox_envlist: gilt

- job:
    name: cfg-generics-tox-check
    parent: tox
    vars:
      BRANCH: "{{ zuul.branch }}"
      tox_envlist: check

- job:
    name: cfg-generics-container-image-inventory-reconciler-push
    parent: abstract-container-image-inventory-reconciler-push
    secrets:
      - name: secret
        secret: SECRET_CFG_GENERICS
        pass-to-parent: true

- job:
    name: cfg-generics-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_CFG_GENERICS
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    gate:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - cfg-generics-tox-check
        - cfg-generics-tox-gilt
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    post:
      jobs:
        - cfg-generics-container-image-inventory-reconciler-push:
            branches: main
        - cfg-generics-container-image-osism-ansible-push:
            branches: main
