---
name: Update images

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install PyYAML + Jinja2
        run: pip3 install PyYAML Jinja2

      - name: Checkout release repository
        run: git clone https://github.com/osism/release

      - name: Create PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            python3 src/update-images.py
          COMMIT_EMAIL: 'bot@osism.io'
          COMMIT_MESSAGE: |
            chore: update versions in environments/manager/images.yml

            Signed-off-by: OSISM Bot <bot@osism.io>
          COMMIT_NAME: 'OSISM Bot'
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: 'update-images'
          PR_BRANCH_PREFIX: 'chore/'
          PR_TITLE: 'chore: update versions in environments/manager/images.yml'
